SOURCES=\
src/PhaseSpace.cpp\
src/MaxwellBoltzmannDistribution.cpp\
src/particleContainer/Cell.cpp\
src/particleContainer/LinkedCellParticleContainer.cpp\
src/particleContainer/ParticleContainer.cpp\
src/particleContainer/SimpleParticleContainer.cpp\
src/test/SimpleParticleContainerTest.cpp\
src/test/LinkedCellParticleContainerTest.cpp\
src/test/TestSettings.cpp\
src/test/ThermostatTest.cpp\
src/test/ParticleContainerTest.cpp\
src/input/InputParameters.cpp\
src/MolSim.cpp\
src/Thermostat.cpp\
src/outputWriter/vtk-unstructured.cpp\
src/outputWriter/XYZWriter.cpp\
src/outputWriter/VTKWriter.cpp\
src/Particle.cpp\
src/ParticleGenerator.cpp\
src/FileReader.cpp\
