/*
 * Particle.cpp
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#include "Particle.h"

#include <sstream>
#include <iostream>
#include <cassert>

log4cxx::LoggerPtr Particle::logger(log4cxx::Logger::getLogger("Particle"));

Particle::Particle(int type_arg) {
	type = type_arg;
	LOG4CXX_DEBUG(logger, "Particle generated");
	f = 0.0;
	old_f = 0.0;
}

Particle::Particle(const Particle& other) {
	x = other.x;
	v = other.v;
	f = other.f;
	old_f = other.old_f;
	m = other.m;
	sigma = other.sigma;
	epsilon = other.epsilon;
	type = other.type;
	LOG4CXX_DEBUG(logger, "Particle generated by copy");
}

// Todo: maybe use initializater list instead of copy?
Particle::Particle(	utils::Vector<double, 3> x_arg,
			utils::Vector<double, 3> v_arg,
			double m_arg,
			double sigma_arg,
			double epsilon_arg,
			int type_arg

) {
	x = x_arg;
	v = v_arg;
	m = m_arg;
	assert(m >= 0);
	sigma = sigma_arg;
	epsilon = epsilon_arg;
	type = type_arg;
	f = 0.0;
	old_f = 0.0;
	LOG4CXX_DEBUG(logger, "Particle generated");
}

Particle::~Particle() {
	LOG4CXX_TRACE(logger, "Particle destructed");
}


std::string Particle::toString() {
	std::stringstream stream;
	stream << "Particle: X:" << x <<  " v: " << v << " f: " << f << " old_f: " << old_f << " mass: " << m << " type: " << type;
	return stream.str();
}

std::ostream& operator<<(std::ostream& stream, Particle& p) {
	stream << p.toString();
	return stream;
}
